### ISSUE TITLE
Missing required argument "[partitions]"

### ISSUE THREAD

**Issue by achintyaakumar** [kavimaluskam/kafka-starter#9]
Hello!
This might be a silly issue but I'm new to Docker and Kafka and I'm trying to run this on a windows machine but it says that the partitions argument in the statement ` kafka-topics --create --topic $TOPIC --partitions 4 --zookeeper $ZK --replication-factor 2` is missing.

**Comment by achintyaakumar** [comment]
Installed Chocolatey, seems to work now!

**Comment by achintyaakumar** [comment]
I wrote `kafka-topics --create --zookeeper $ZK --replication-factor 2 --partitions 4 --topic $TOPIC` instead and it worked, don't know what the problem was

**Comment by kavimaluskam** [comment]
Hey sorry for my late feedback. @achintyaakumar 
Have you solved the issue? Are you working on Windows or WSL2?
